[CI] Add auto detection of craft package name
The craft package name is extracted by default it the merge request
or commit message title is setup as '[<package>] Description'.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -119,7 +119,20 @@ build-package-linux:
     KDECI_CRAFT_PLATFORM: linux-64-gcc
     GIT_STRATEGY: none
   before_script:
-    - if [ -z "$CRAFT_PACKAGE" ]; then echo "Error - Set CRAFT_PACKAGE environment variable to the package you want to test."; false; fi
+    - |
+      if [ -z "$CRAFT_PACKAGE" ]; then
+        TITLE="${CI_MERGE_REQUEST_TITLE:-$CI_COMMIT_TITLE}"
+        CRAFT_PACKAGE="$(echo "$TITLE" | sed -n 's/^\[\([^]]\+\)\].*/\1/p')"
+        export CRAFT_PACKAGE
+      fi
+    - |
+      if [ -z "$CRAFT_PACKAGE" ]; then
+        echo "Error: Unable to determine CRAFT_PACKAGE."
+        echo "Expected commit/MR title format: [package] Description"
+        echo "or set CRAFT_PACKAGE environment variable to the package you want to test"
+        exit 1
+      fi
+    - echo "Using CRAFT_PACKAGE=$CRAFT_PACKAGE"
     - export LANG=en_US.UTF-8
     - git clone https://invent.kde.org/packaging/craftmaster.git --branch=master
     - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
@@ -165,7 +178,21 @@ build-package-linux:
     PYTHONUTF8: 1
     KDECI_CRAFT_CACHE: C:/Craft/download/
   before_script:
-    - if (-not $env:CRAFT_PACKAGE) { Write-Error "Error - Set CRAFT_PACKAGE environment variable to the package you want to test."; exit 1 }
+    - |
+      if (-not $env:CRAFT_PACKAGE) {
+          $title = $env:CI_MERGE_REQUEST_TITLE
+          if (-not $title) { $title = $env:CI_COMMIT_TITLE }
+          Write-Host "Deriving CRAFT_PACKAGE from title: $title"
+          if ($title -match '^\[([^\]]+)\]') {
+              $env:CRAFT_PACKAGE = $matches[1]
+              Write-Host "Using CRAFT_PACKAGE=$($env:CRAFT_PACKAGE)"
+          } else {
+              Write-Error "Error: Unable to determine CRAFT_PACKAGE."
+              Write-Error "Expected commit/MR title format: [package] Description"
+              Write-Error "or set CRAFT_PACKAGE environment variable to the package you want to test"
+              exit 1
+          }
+      }
     - cd C:\Craft\craftmaster
     - git pull
     - cd C:\Craft\ci-utilities
@@ -229,7 +256,19 @@ build-package-windows_qt6_mingw64:
   variables:
     GIT_STRATEGY: none
   before_script:
-    - if [ -z "$CRAFT_PACKAGE" ]; then echo "Error - Set CRAFT_PACKAGE to the package you want to test."; false; fi
+    - |
+      if [ -z "$CRAFT_PACKAGE" ]; then
+        TITLE="${CI_MERGE_REQUEST_TITLE:-$CI_COMMIT_TITLE}"
+        CRAFT_PACKAGE="$(echo "$TITLE" | sed -n 's/^\[\([^]]\+\)\].*/\1/p')"
+        export CRAFT_PACKAGE
+      fi
+    - |
+      if [ -z "$CRAFT_PACKAGE" ]; then
+        echo "Error: Unable to determine CRAFT_PACKAGE."
+        echo "Expected commit/MR title format: [package] Description"
+        echo "or set CRAFT_PACKAGE environment variable to the package you want to test"
+        exit 1
+      fi
     # ensure we start with an empty folder
     - rm -rf *
     - export LANG=en_US.UTF-8
@@ -292,7 +331,19 @@ build-package-macos_qt6_x86_64:
   variables:
     GIT_STRATEGY: none
   before_script:
-    - if [ -z "$CRAFT_PACKAGE" ]; then echo "Error - Set CRAFT_PACKAGE to the package you want to test."; false; fi
+    - |
+      if [ -z "$CRAFT_PACKAGE" ]; then
+        TITLE="${CI_MERGE_REQUEST_TITLE:-$CI_COMMIT_TITLE}"
+        CRAFT_PACKAGE="$(echo "$TITLE" | sed -n 's/^\[\([^]]\+\)\].*/\1/p')"
+        export CRAFT_PACKAGE
+      fi
+    - |
+      if [ -z "$CRAFT_PACKAGE" ]; then
+        echo "Error: Unable to determine CRAFT_PACKAGE."
+        echo "Expected commit/MR title format: [package] Description"
+        echo "or set CRAFT_PACKAGE environment variable to the package you want to test"
+        exit 1
+      fi
     - git clone https://invent.kde.org/packaging/craftmaster.git --branch=master
     - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
     - git clone https://invent.kde.org/sysadmin/craft-ci.git --depth=1
